### ISSUE TITLE
Change default merge strategy to squash

### ISSUE THREAD

**Issue by inverse** [paulotruta/jee-pee-tee#16]
In order to have more linear history and cleaner ways to revert and see what changed we could change the default merge strategy to squash.

**Comment by paulotruta** [comment]
Changed the Pull Request merge settings to be:
<img width="817" alt="Screenshot 2022-12-10 at 13 50 28" src="https://user-images.githubusercontent.com/1270431/206856019-120daeae-ca9e-48a4-b9b9-c89127ce553e.png">

I chose to add PR title and commits to the merge message.
Let me know if this looks good 👍

**Comment by paulotruta** [comment]
<img width="992" alt="Screenshot 2022-12-10 at 13 58 47" src="https://user-images.githubusercontent.com/1270431/206856339-19dfd1da-f0ae-4a21-9d97-43fbc59aa7a9.png">

After merging the latest PR, we have the first example of the Squash merge. Looks good! 🎉

**Comment by inverse** [comment]
Awesome!
